### ISSUE TITLE
Add Pouria

### ISSUE THREAD

**Issue by Pnsadeghy** [nekofar/awesome-freelancers#99] opened 2019-10-07 13:29 UTC
Backend: Laravel - Asp mvc - .Net core - Node.js
Frontend: Vuejs - Angular - Html5 - css3 - jquery

pnsadeghy@gmail.com
telegram: @Pnsadeghy
twitter: @MyLittleDesk

**Comment by nekofar** [comment] 2019-10-07 13:43
Duplicate of #89

**Closed** 2019-10-08 20:22 UTC
Labels: duplicate
